Feature/31 update to current 5x remove form from build
cloudogu/swaggerui pull request #32
Opened 2024-09-27 06:14 UTC by notmyown

2024-10-01 10:26 UTC, notmyown commented
since the dogu is not depending on the swagger-ui fork anymore, the custom cloudogu styling would be lost. Therfore a new css file was added to the index template of the swagger-dogu.

By analysing the SCSS Rules and mixins, all compiled css classes are configured to use the custom cloudogu colors

![grafik](https://github.com/user-attachments/assets/ba89252c-4f48-4793-b7eb-cdaf77c72284)

so the official swagger-ui archive can be used along with the custom cloudogu theme

2024-10-14 13:13 UTC, ppxl requested changes
Hi, thanks for the great work! I found only some minor issues. Anyhow, there seem to exist some issues with the unix permissions because all files received the executable bit which is not quite ideal.

2024-10-14 13:13 UTC, ppxl commented on CHANGELOG.md
> +- dismiss special fork from swagger-ui (#31)
yes! :muscle:

2024-10-14 13:13 UTC, ppxl commented on Dockerfile
>  FROM registry.cloudogu.com/official/base:3.20.2-1 as swaggerui
This image could be newer with fewer CVEs.
```suggestion
FROM registry.cloudogu.com/official/base:3.20.3-2 as swaggerui
```

2024-10-14 13:13 UTC, ppxl commented on Dockerfile
>  FROM registry.cloudogu.com/official/base:3.20.2-1
As above: 
```suggestion
FROM registry.cloudogu.com/official/base:3.20.3-2
```

2024-10-14 13:13 UTC, ppxl commented on docs/development/local_setup_de.md
> +Im Dockerfile des Gogus wird nur noch die entsprechende Version angepasst.
Typo:
```suggestion
Im Dockerfile des Dogus wird nur noch die entsprechende Version angepasst.
```

2024-10-14 13:13 UTC, ppxl commented on docs/development/local_setup_en.md
> +```
This content does not seem like a literal translation of the german variant. Why the difference?

2024-10-14 13:13 UTC, ppxl commented on dogu.json
`100644 → 100755 `
Is there are reason for the general setting of the executable bit in all files of this change? There aren't even executable files among this change set.

2024-10-18 08:41 UTC, ppxl commented
LGTM, thanks for the work :blue_heart:

2024-10-18 08:41 UTC, merged